server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.26.130:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    show-sql: true
    database: mysql
  rabbitmq:
    host: 192.168.26.129
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8686/eureka/ 