server: 
  port: 9008
spring: 
  application:  
    name: tensquare-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.26.130:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: root
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.26.130
  rabbitmq:
    host: 192.168.26.130
jwt:
  config:
    key: lizhijie
    ttl: 360000
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://192.168.26.130:8686/eureka/