server:
  port: 9012
spring:
  application:
    name: tensquare-web
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://192.168.26.130:8686/eureka/
zuul:
  routes:
    tensquare-base:
      path: /base/**
      serviceId: tensquare-base
    tensquare-user:
      path: /user/**
      serviceId: tensquare-user
    tensquare-qa:
      path: /qa/**
      serviceId: tensquare-qa
    tensquare-article:
      path: /article/**
      serviceId: tensquare-article
    tensquare-friend:
      path: /friend/**
      serviceId: tensquare-friend
    tensquare-gathering:
      path: /gathering/**
      serviceId: tensquare-gathering
    tensquare-recruit:
      path: /recruit/**
      serviceId: tensquare-recruit
    tensquare-search:
      path: /search/**
      serviceId: tensquare-search
    tensquare-spit:
      path: /spit/**
      serviceId: tensquare-spit
  sensitive-headers:
    - Cookie
    - Set-Cookie
#    - Authorization